name: Backend Prod Deploy

on:
  workflow_dispatch:

jobs:
  approval:
    name: Wait For Manual Approval
    runs-on: ubuntu-latest

    steps:
      - name: Require Approval Before Production Deploy
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: khakindrad
          minimum-approvals: 1
          issue-title: "PRODUCTION DEPLOYMENT APPROVAL"
          issue-body: "Approve this request to deploy backend to PRODUCTION."

  deploy:
    name: Deploy to EC2 (Production)
    needs: approval
    runs-on: u
