name: Backend Prod Deploy

on:
  workflow_dispatch:

jobs:
  approval:
    name: Require Manual Approval
    runs-on: ubuntu-latest

    steps:
      - name: Approve Production Deployment
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: khakindrad      # Change if needed
          minimum-approvals: 1
          issue-title: "PROD Deployment Approval Needed"
          issue-body: "Approve to deploy backend to EC2 production server."

  deploy:
    name: Deploy to EC2 (Production)
    needs: approval
    runs-on: ubuntu-latest

    steps:
      - name: Download Latest Release ZIP
        uses: robinraju/release-downloader@v1
        with:
          latest: true
          repository: ${{ github.repository }}
          filename: "backend-release.zip"

      - name: Extract ZIP
        run: unzip backen
