name: Deploy Backend to Production

on:
  workflow_dispatch:

jobs:
  approval:
    name: Wait For Manual Approval
    runs-on: ubuntu-latest

    steps:
      - name: Require Approval Before Prod Deploy
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: khakindrad
          minimum-approvals: 1
          issue-title: "Production Deployment Approval Needed"
          issue-body: "Approve this request to deploy backend to production."

  deploy:
    name: Deploy to Production EC2
    needs: approval
    runs-on: ubuntu-latest

    steps:
      - name: Download Latest Release Build
        uses: robinraju/release-downloader@v1
        with:
          latest: true
